### ISSUE TITLE
Backlight on LineageOS port.

### ISSUE THREAD

**Issue by azarok** [TomJansen/Qin-F21-Pro-Backlight-enabler#1]
The backlight keypad is constantly on in the LineageOS port for the Qin F21, which quickly drains the battery. Will this module turn on the keypad backlight only when the screen is on and leave the backlight off otherwise?
Will it also work on the Qin F22?
Many thanks

**Comment by TomJansen** [comment]
Hi. Thanks for the interest.

I do not know if this module will work on the LineageOS port, as I do not use LineageOS. But as far as I know, testing this module will be relatively safe. The same holds true for the Qin F22. I do not have that device. If somebody tests this, I will update the README to mention if it works or not.

>Will this module turn on the keypad backlight only when the screen is on and leave the backlight off otherwise?

Yes. The code in this module will set a certain base value on the backlight brightness when the screen is on. When the screen is off, the code will set the brightness value to 0.

**Comment by azarok** [comment]
I sincerely appreciate your speedy response.
As soon as I have the F22, I'll surely test the module.
Can the module be installed without rooting the phone (and install Magisk) using TWRP?
Once more, many thanks.

**Comment by TomJansen** [comment]
>Can the module be installed without rooting the phone (and install Magisk) using TWRP?

This module echos values to `/sys/class/leds/mt6370_pmu_led1/brightness`, so I do not think this will work without root

**Comment by azarok** [comment]
Okay, many thanks for your help.

**Comment by SlingShot713** [comment]
> > Can the module be installed without rooting the phone (and install Magisk) using TWRP?
> 
> This module echos values to `/sys/class/leds/mt6370_pmu_led1/brightness`, so I do not think this will work without root

Ah shoot.  The backlight is the only thing keeping me from using the f22 pro full time.  I'd be happy to test anything out.  I jsut need to figure out rooting the f22.
